import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import {buildHarness,initRepo} from './helpers.mjs';
import {AmplifyStaticDelivery,validateSmokeHtml} from '../src/pipeline/staticStaging.mjs';
const s={enabled:true,mode:'static-smoke',accountId:'123456789012',appId:'dtest',appName:'bello-orchestrator-smoke',branch:'preview-orchestrator',region:'us-west-2',profile:'test',isolatedDataConfirmed:true,maxWaitSeconds:600};
test('static HTML blocks executable, remote and escaped markup',()=>{validateSmokeHtml('<html><p>BELLO</p></html>');for(const x of ['<script>BELLO</script>','<p onclick="x">BELLO</p>','<p>BELLO &lt;</p>','<p>BELLO https://x</p>'])assert.throws(()=>validateSmokeHtml(x));});
test('static preflight rejects repository, roles, variables and backend',async()=>{const app={appArn:'arn:aws:amplify:us-west-2:123456789012:apps/dtest',name:s.appName,platform:'WEB'};const branch={branchName:s.branch,stage:'DEVELOPMENT',enableAutoBuild:false};const d=new AmplifyStaticDelivery({config:{staging:s}});d.call=async op=>op==='get-app'?{app}:{branch};await d.preflight();for(const [obj,key,val] of [[app,'repository','https://github.com/x/y'],[app,'iamServiceRoleArn','role'],[app,'environmentVariables',{TOKEN:'x'}],[branch,'backend',{stackArn:'stack'}],[branch,'enableAutoBuild',true]]){obj[key]=val;await assert.rejects(d.preflight());delete obj[key];}});
async function setup(){const h=await buildHarness();initRepo(h.config.repoPath);fs.unlinkSync(h.config.repoPath+'/README.md');fs.writeFileSync(h.config.repoPath+'/index.html','<html><p>BELLO</p></html>');spawnSync('git',['add','-A'],{cwd:h.config.repoPath});spawnSync('git',['commit','-qm','static'],{cwd:h.config.repoPath});const task=h.repo.createTask({title:'static',instruction:'test',repoPath:h.config.repoPath}).task;Object.assign(task,{work_dir:h.config.repoPath,isolation:'worktree',git_end_commit:spawnSync('git',['rev-parse','HEAD'],{cwd:h.config.repoPath,encoding:'utf8'}).stdout.trim()});const d=new AmplifyStaticDelivery({config:{staging:s},repo:h.repo,verifier:{required:true,check:()=>({passed:true})}});return {h,task,d};}
test('real artifact upload and HTTP hash gate, persisted job and restart',async()=>{const {h,task,d}=await setup();try{let starts=0;d.preflight=async()=>{};d.call=async op=>{if(op==='create-deployment')return {jobId:'1',zipUploadUrl:'https://bucket.s3.amazonaws.com/upload'};if(op==='start-deployment'){starts++;return {}};return {job:{summary:{jobId:'1',status:'SUCCEED'}}}};d.request=async(_url,opts)=>{if(opts.method==='PUT'){assert.equal(opts.body.readUInt32LE(0),0x04034b50);return {ok:true}}return new Response('<html><p>BELLO</p></html>')};assert.equal(d.prepare(task).state,'ready');assert.equal((await d.advance(task)).state,'running');assert.equal((await d.advance(task)).state,'succeeded');assert.equal(starts,1);assert.ok(h.repo.store.get("SELECT data FROM checkpoints WHERE phase='static_http'"));}finally{h.cleanup()}});
test('ambiguous dispatch is not retried and wrong HTTP content cannot complete',async()=>{const {h,task,d}=await setup();try{d.prepare(task);d.update(task.id,'starting',null,'7');d.call=()=>assert.fail('no redispatch');assert.equal((await d.advance(task)).state,'blocked');d.update(task.id,'running',null,'7');d.call=async()=>({job:{summary:{jobId:'7',status:'SUCCEED'}}});d.request=async()=>new Response('wrong');assert.equal((await d.advance(task)).state,'running');fs.writeFileSync(task.work_dir+'/unexpected.txt','not allowed');assert.equal((await d.advance(task)).state,'blocked');assert.notEqual(d.row(task.id).state,'succeeded');}finally{h.cleanup()}});
test('bounded main repo deploys only the explicit safe evidence artifact',async()=>{const h=await buildHarness();try{initRepo(h.config.repoPath);fs.mkdirSync(h.config.repoPath+'/docs',{recursive:true});fs.writeFileSync(h.config.repoPath+'/docs/eco-status.html','<html><p>BELLO verified staging evidence</p></html>');spawnSync('git',['add','docs/eco-status.html'],{cwd:h.config.repoPath});spawnSync('git',['commit','-qm','evidence'],{cwd:h.config.repoPath});const task=h.repo.createTask({title:'main',instruction:'test',repoPath:h.config.repoPath}).task;Object.assign(task,{work_dir:h.config.repoPath,isolation:'worktree',git_end_commit:spawnSync('git',['rev-parse','HEAD'],{cwd:h.config.repoPath,encoding:'utf8'}).stdout.trim()});const settings={...s,sourceMode:'bounded-main',artifactPath:'docs/eco-status.html'};const d=new AmplifyStaticDelivery({config:{staging:settings},repo:h.repo,verifier:{required:true,check:()=>({passed:true})}});assert.equal(d.artifact(task).artifactPath,'docs/eco-status.html');}finally{h.cleanup()}});

