<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PhotoStation.Domain\PhotoStation.Domain.csproj" />
    <ProjectReference Include="..\PhotoStation.Application\PhotoStation.Application.csproj" />
    <ProjectReference Include="..\PhotoStation.Infrastructure\PhotoStation.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
