import { createServerRunner } from "@aws-amplify/adapter-nextjs";
// Generated by `npx ampx sandbox` (local dev) or the Amplify Hosting build
// (deployed branches) — see README.md. Not committed; run the sandbox
// command once before `npm run dev` if this import errors on a fresh
// checkout.
import outputs from "@/amplify_outputs.json";

export const { runWithAmplifyServerContext } = createServerRunner({
  config: outputs,
});
