const CODES = new Set([
  "ACCOUNT_MISMATCH", "NAVIGATION_UNVERIFIED", "HEADING_TIMEOUT", "HEADING_NOT_UNIQUE",
  "NEXT_BUTTON_TIMEOUT", "NEXT_BUTTON_NOT_UNIQUE", "DOCUMENT_URL_UNVERIFIED",
  "PAGE_URL_UNVERIFIED", "FIELD_ROWS_INVALID", "TITLE_UNOBSERVED",
  "DESCRIPTION_UNOBSERVED", "INVENTORY_CODE_UNOBSERVED", "PRICE_FIELD_NOT_EXTRACTED",
  "PRICE_FORMAT_UNSUPPORTED", "QUANTITY_MULTIPLE_VARIANTS",
  "QUANTITY_FIELD_NOT_EXTRACTED", "QUANTITY_FORMAT_UNSUPPORTED",
  "PRIVATE_TITLE_UNOBSERVED", "PRIVATE_LIST_URL_UNVERIFIED", "PRIVATE_TABLE_NOT_FOUND",
  "PRIVATE_TABLE_MULTIPLE", "PRIVATE_TABLE_NOT_NATIVE", "PRIVATE_HEADER_ROW_UNVERIFIED",
  "PRIVATE_HEADER_CELL_COUNT", "PRIVATE_HEADER_SHAPE", "PRIVATE_HEADER_NAME_UNVERIFIED",
  "PRIVATE_HEADER_TITLE_PAIR",
  "PRIVATE_ROW_NOT_FOUND", "PRIVATE_ROW_MULTIPLE", "PRIVATE_ROW_NOT_NATIVE",
  "PRIVATE_ROW_PARENT_UNVERIFIED", "PRIVATE_ROW_CELL_COUNT", "PRIVATE_ROW_CELL_SHAPE",
  "PRIVATE_IMAGE_CELL_SHAPE", "PRIVATE_IMAGE_ALT_UNVERIFIED",
  "PRIVATE_TITLE_TEXT_CELL_SHAPE", "PRIVATE_TITLE_CELL_TEXT", "PRIVATE_TITLE_PARAGRAPH_TEXT",
  "PRIVATE_STATUS_CELL_TEXT", "PRIVATE_STATUS_PARAGRAPH_COUNT",
  "PRIVATE_STATUS_PARAGRAPH_TEXT", "PRIVATE_TITLE_CELL_MISSING", "PRIVATE_RETURN_ID_UNVERIFIED",
  "PRIVATE_READ_FAILED",
]);

/** Local, fixed-code diagnostics only. Never accepts URLs, labels, or field values. */
export function safeReadDiagnostics(input) {
  return Array.isArray(input) ? [...new Set(input.filter(code => CODES.has(code)))].slice(0, 8) : [];
}
